"""Chatbot knowledge base: ~64 Q/A pairs about wind/solar/hydro ops.
Exported as JSON; TF-IDF vectors built in train_models.py -> ml/models/chatbot.json
"""
KB = [
 ("how to detect energy theft", "Compare SCADA dispatch vs consumer-meter totals per feeder. A sudden >12% shortfall or >7% sustained deficit = probable tapping. Patrol the worst feeder at night, check HV protocol, then file a Complaint on the website against the distribution authority."),
 ("what is transmission loss norm", "Keep transmission loss under 5% (max 8%). Transmit at HV 132-220 kV to cut I2R loss, shorten feeders, inspect joints. Our AI flags >8% as danger, 5-8% as warning."),
 ("battery health low what to do", "Health (SOH) below 75% means replace strings. 75-85%: schedule cell balancing + thermal check and plan augmentation. Always keep emergency reserve >=15% of capacity and SoC between 20-90%."),
 ("emergency storage how much", "Keep 15% of battery capacity as emergency reserve, untouched except in blackouts or global-contingency events. The Storage stage shows it separately; AI raises a danger alert below 10%."),
 ("solar rain what to do", "If rain >2mm is forecast: tilt panels to drain mode, enable lightning protection, pause cleaning robots. After rain, wash dust-mud film — it restores ~6% yield."),
 ("wind low speed what to do", "Below 12 km/h: run only high-efficiency turbines, park the rest to save yaw wear. Benefit window is only 2-4 hrs. Above 90 km/h: feather blades and shut down."),
 ("wind storm protection", "Storm wind above 90 km/h: feather blades, yaw out of wind, shut down to protect the gearbox. Zero-benefit window until the storm passes. Log it as a forecast-stage problem."),
 ("hydro heavy rain", "Upstream rain >20mm: dam level rises fast — open controlled release through turbines NOW and convert inflow to power. A dam cannot hold flood water long."),
 ("hydro low flow", "River flow below 60 cumec: run a single turbine at best-efficiency point and store dam reserve. Above 150 cumec: run all penstocks 12-20 hrs."),
 ("maintenance schedule windmill", "Greasing/oiling + alignment every 180 days or when efficiency <86%. Vibration >4.5 mm/s = stop unit, bearing fault likely. Age >15 yrs = replace."),
 ("solar panel maintenance", "Deep cleaning + PID check when efficiency <86%, within 7 days. Bifacial TOPCon 580W panels give +11% cloudy-day yield vs old PERC."),
 ("how to boost production", "Wind: direct-drive turbines (no gearbox) + smart-twist blades for low wind. Solar: TOPCon bifacial + aggressive MPPT tracking. Hydro: Kaplan runner upgrade (+9% at same flow). Hybrid wind-solar + pumped hydro storage cuts battery cost ~30%."),
 ("what tolerance for data", "Calculated-vs-actual deviation within ±7% is tolerated (minor deficit 2-7% just noted). 2+ stages breaching, or worst >20%, = FAULTY, uploader must explain. This catches fake data and theft."),
 ("daily upload reminder", "Uploaders must upload every day before 18:00: weather (past+today+forecast), production kW + hours, storage + emergency kW, transmission per destination. A missed day is flagged as inconsistency."),
 ("small scale vs large scale", "Small Scale = e.g. a university hostel or campus microgrid. Large Scale = a city utility or industrial cluster. Pick it once at registration; it tags all uploads and decisions."),
 ("roles on website", "Roles: Admin (approves, decides), Weather uploader, Production uploader, Storage uploader, Transmission uploader. Each sees only its upload form + a personal dashboard."),
 ("forecast production storage distribution meaning", "The universal flow: Forecast (weather risk) -> Production (generate) -> Storage (batteries + emergency) -> Distribution (HV lines to hostel rooms, street lights, food court). Click each stage in Energy Tracking."),
 ("how approvals work", "AI detects a problem, writes what/why/how + past handling + solution + aim. Admin clicks Approve, Reject (reason required — trains AI), or Make-a-Solution (write own plan, AI learns it)."),
 ("what is ai desk", "AI Desk is the research chat: ask anything, gather insights, draft your own solution before submitting it in Approvals. Every chat is logged as a learning."),
 ("how to file complaint", "Complaints page: pick source + stage, write what happened (e.g. energy theft on feeder B), submit. It is stored with date and shown in admin history — use it against the distribution authority."),
 ("how feedback works", "Feedback page: rate the website/system/AI 1-5 and write suggestions. History is visible so the admin keeps a work diary."),
 ("kolkata delhi mumbai hyderabad weather", "Forecasts page shows live Open-Meteo data for Kolkata, Delhi, Mumbai, Hyderabad: past 7 days (archive), present current, future 7-day forecast, plus per-source impact notes."),
 ("solar peak hours", "Peak solar 10:00-15:30 on clear days (cloud <20%, no rain). Keep optimal tilt, MPPT aggressive tracking on partial-cloud days."),
 ("battery cycles high", "Cycles >4000: derate charge to 0.5C to extend life. Avoid >25% surplus over demand — surplus raises holding cost and wastage."),
 ("capacity vs demand", "Keep capacity >=1.3x demand for net-zero buffer. If capacity <1.1x demand, AI asks for augmentation in MWh numbers."),
 ("what is soc", "SoC = stored/capacity %. Keep 20-90%. Above 95% with low demand = trim generation setpoint 5% and move surplus to emergency reserve."),
 ("how ai detects problems", "Model 1 (problem detector, trained on 1200-row dataset) scores every stage daily from weather + equipment + battery + distribution features. Breaches become red-flag problems with severity."),
 ("how ai makes solutions", "Model 2 (solution model) maps each problem class to a fix template with numbers (hours, voltages, MWh). Admin approves/rejects; rejections and manual solutions retrain its preferences."),
 ("gemini integration", "Optionally paste a free Gemini API key in AI Desk / Forecasts to get richer explanations. Without a key the built-in trained models handle everything offline."),
 ("adamas hostel example", "Example: hostel needs 23 kW. Produced 30, stored 25 + emergency 5, distributed 23 (rooms 15 + lights 7 + food court 1). Extra 2 kW unaccounted = AI flags possible theft for approval."),
 ("street light allocation", "Typical small-scale split: hostel rooms ~60%, street lights ~30%, food court ~10%. Transmission uploader logs each destination daily; totals must match sent kWh within 7%."),
 ("monsoon outlook", "Long-range: monsoon +45-day outlook usually means hydro surplus in 6-9 weeks — pre-plan turbine availability and defer major hydro outage."),
 ("heatwave outlook", "Heatwave +30-day outlook: solar +18%, wind -12%. Shift maintenance to wind units during the lull; derate solar inverters 2% for heat."),
 ("solid state battery", "Solid-state pilot (500 kWh at city station): 2x density, 15-min response for emergency reserve. Ecosystem upgrade suggestion from AI Insights."),
 ("hvdc upgrade", "AI HVDC dynamic line rating raises corridor capacity 15-25% without new towers; transmission loss drops ~2 points."),
 ("cleaning robots solar", "Pause cleaning robots during rain; resume with deep wash after. Cleaning cycles restore ~6% yield lost to dust."),
 ("pid check solar", "Potential-induced degradation check when efficiency drifts: strings below 86% get PID test + deep clean within 7 days."),
 ("bearing fault wind", "Vibration >4.5 mm/s = bearing fault likely. Stop unit, inspect, order bearings. 4-hr greasing shutdown restores ~4% efficiency."),
 ("dam rationing", "Low-flow weeks need dam rationing: single-turbine best-efficiency operation, store reserve, defer non-essential releases."),
 ("mppt tracking", "On partial-cloud days enable aggressive MPPT tracking and stagger inverter startup to catch fast irradiance swings."),
 ("transformer role", "Transformers step HV 132-220 kV down to hostel/campus voltage. Skipping HV step (e.g. 11 kV direct) violates protocol and raises loss — flagged danger."),
 ("scada vs meter", "SCADA = what was sent; meter = what arrived. Gap >7% sustained or >12% sudden = investigate. Our roadmap table shows both per stage."),
 ("fake data guard", "Calculated values (physics estimate) vs actual (uploader numbers): ±7% tolerated. Breaches flagged FAULTY; uploader must file written explanation before settlement."),
 ("oiling frequency", "Wind/hydro rotating machines: oiling/greasing at least every 180 days; direct-drive and magnetized bearings halve the frequency."),
 ("panel tilt monsoon", "Monsoon: steeper tilt drains water faster and sheds mud. Track forecast; switch to drain mode when rain >2mm predicted."),
 ("penstock operation", "Normal flow: 2 turbines 8-12 hrs. Strong flow >150 cumec: all 3 penstocks 12-20 hrs. Low flow <60: single turbine best-efficiency."),
 ("feeder patrol", "Night patrol of worst-deviation feeder: look for illegal tapping, burnt joints, bypassed meters. Log findings as a Complaint + Manual decision."),
 ("approve vs reject", "Approve = execute AI plan. Reject = must give reason (trains AI). Make-a-Solution = admin writes own plan; AI studies it and adjusts future suggestions."),
 ("who can approve", "Only admin role can approve/reject. Uploaders only upload; they cannot approve."),
 ("login help", "Home -> Login -> pick scale (Large/Small) -> pick role (Admin / 4 uploaders) -> login or create account. Demo admin: admin@renew.io / admin123."),
 ("loading screens", "Route changes show a loading scene (spinner + stage tips) so data fetches never look frozen."),
 ("contact us", "Contact section at the bottom of Home: email + phone of the project team."),
 ("game tips renewables", "Home shows rotating tips: what renewables are, why they matter, how weather affects output — slides every 5 seconds."),
 ("what is renewable energy", "Renewable = sun, wind, water flows that refill naturally. Keyентов: no fuel cost, low carbon, but weather-varying — hence forecasting + storage."),
 ("why weather matters", "Cloud cuts solar, calm cuts wind, rain swells hydro. The Forecast stage converts weather into ops windows (which source to prioritize each day)."),
 ("windmill parts", "Blades -> hub -> gearbox (or direct-drive) -> generator -> yaw. Gearbox and bearings need most maintenance."),
 ("solar parts", "Panels -> MPPT -> inverter -> battery -> distribution. Inverter heat-derating matters in heatwaves."),
 ("hydro parts", "Dam -> penstock -> turbine runner -> generator -> HV step-up. Runner and magnetized bearings decide efficiency."),
 ("net zero buffer", "Net-zero buffer = capacity 1.3x demand so a cloudy+calm day still meets load from storage + emergency reserve."),
 ("holding cost battery", "Surplus stored far above demand raises holding cost and cycle wear. AI suggests trimming setpoint instead of over-storing."),
 ("distribution score", "Distribution score = 100 - loss% - protocol penalties. Shown per source in the Distribution stage with performance label."),
 ("health bar meaning", "Health bars: equipment efficiency%, battery SOH%, each stage score 0-100. Red <60, amber 60-80, green >80."),
 ("predicted problems", "Each stage lists predicted problems (ML forecast for next 3-7 days) separately from active problems, with confidence %."),
 ("past handling", "Every problem card shows if it occurred before and how it was handled — from decisions history — so admin repeats what worked."),
 ("manual solution learning", "When admin writes a manual solution, the chatbot model stores it; future similar problems quote it back as 'learned from admin'."),
 ("night vs day ops", "Solar day-peaks charge batteries; wind often night-peaks; hydro is dispatchable. Night hostel load runs mostly on stored + wind."),
 ("food court load", "Food-court load is spiky (meal hours). Keep 10% headroom in distribution plan; log it separately in transmission uploads."),
 ("how to register", "Login page: select scale first, then role, then Create account (name/email/password) or Login. Scale+role are stored with the user."),
]
